# Generated by Django 5.2.7 on 2025-11-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_options_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='midtrans_order_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='midtrans_payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='midtrans_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='midtrans_snap_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='midtrans_transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='midtrans_transaction_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('midtrans', 'Midtrans (Kartu/E-Wallet/Transfer)'), ('bank_transfer', 'Transfer Bank Manual'), ('cash', 'Cash'), ('cod', 'Cash On Delivery')], default='midtrans', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('verifying', 'Sedang Diverifikasi'), ('success', 'Berhasil'), ('failed', 'Gagal'), ('refunded', 'Dikembalikan'), ('expired', 'Kadaluarsa')], default='pending', max_length=20),
        ),
    ]
