# Generated by Django 5.2.7 on 2025-10-17 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_alter_product_category'),
        ('shop', '0002_category_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
