# Generated by Django 5.2.7 on 2025-10-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price_per_portion',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
