# Generated by Django 5.2.7 on 2025-10-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Catatan khusus untuk pesanan'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price_per_portion',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Harga per porsi saat ditambahkan ke cart', max_digits=12, null=True),
        ),
    ]
