# Generated by Django 5.2.7 on 2025-10-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Alamat pengiriman'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Tanggal pengiriman yang dipilih user', null=True),
        ),
    ]
