# Generated by Django 5.2.7 on 2025-10-31 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_delivery_address_cartitem_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='delivery_date',
        ),
    ]
